FROM python:3.11-alpine3.18

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt --index-url "http://localhost:8081/repository/pypi/simple"
RUN rm requirements.txt

COPY src src

CMD ["python3", "-m", "src"]
