name: Create release

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build-and-release:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'

      - name: Install dependencies
        run: |
          make install

      - name: Build
        run: |
          make build-all

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/

      - name: "Release"
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/*
          generateReleaseNotes: true
